spring.application.name=api

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/pulse
spring.datasource.username=pulse
spring.datasource.password=pulse

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false

spring.flyway.enabled=true

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000